# Basic webscraping example

This notebook is an introductory exploration notebook. In this notebook, we look at the CSV provided by the course instructors, run their example scraping script, experiment with scraping the first 50 URLs, and split the URLs into CSVs for just Fox News and just NBC news (only wrote Fox News to CSV).

Since we have ~4000 urls to scrape, we should probably have some type of standard throttle with a retry/backoff for difficult links. Might be good to split the data into thirds and run separately to reduce the amount of time for each of us.

## Load data

Basic loading and looking at data. Data is a DF with 3000+ links in a `url` column.

In [2]:
import pandas as pd
links = pd.read_csv("../data/external/url_only_data.csv")

list(links["url"])

['https://www.foxnews.com/lifestyle/jack-carrs-eisenhower-d-days-memo-noble-undertaking',
 'https://www.foxnews.com/entertainment/bruce-willis-demi-moore-avoided-doing-one-thing-while-co-parenting-daughter-says',
 'https://www.foxnews.com/politics/blinken-meets-with-qatars-prime-minister.print',
 'https://www.foxnews.com/entertainment/emily-blunt-says-toes-curl-when-people-their-kids-want-act-want-say-dont-do-it',
 'https://www.foxnews.com/media/the-view-co-host-cnn-commentator-ana-navarro-host-night-2-democratic-national-convention',
 'https://www.foxnews.com/politics/striking-boeing-workers-boo-after-democrat-sen-maria-cantwell-criticizes-trump.print',
 'https://www.foxnews.com/politics/white-house-grilled-harris-gun-ownership-mandatory-gun-buybacks.print',
 'https://www.foxnews.com/media/tom-cotton-turns-tables-cnns-dana-bash-guns-brings-up-harris-past-remarks-school-shootings',
 'https://www.foxnews.com/politics/kamala-rides-tsunami-positive-press-skeptics-see-risky-choice',
 'https://www.foxnews.com/politics/harris-running-mate-faces-renewed-scrutiny-weird-socialism-comparison-resurfaces',
 'https://www.foxnews.com/world/israeli-american-reservist-killed-hezbollah-missile-israel-idf-says',
 'https://www.foxnews.com/us/david-mccullough-american-historian-presidential-medal-freedom-recipient-dies',
 'https://www.foxnews.com/politics/lorie-smith-web-designer-free-speech',
 'https://www.foxnews.com/entertainment/simon-cowell-reveals-son-changed-judging-style-empathy',
 'https://www.foxnews.com/lifestyle/walking-dead-syndrome-rare-conditions-baffle-doctors-researchers',
 'https://www.foxnews.com/media/cnn-calls-out-harris-using-trumps-border-wall-campaign-ad-after-condemning-years',
 'https://www.foxnews.com/entertainment/taylor-swift-steals-nyc-spotlight-dinner-blake-lively-sophie-turner-brittany-mahomes',
 'https://www.foxnews.com/health/ozempic-happy-drug-study-suggests-weight-loss-medications-reduce-depression-anxiety',
 'https://www.foxnews.com/food-drink/pennsylvania-family-sickened-after-eating-toxic-mushrooms-expected-recover.print',
 'https://www.foxnews.com/health/family-selling-dream-home-fund-life-saving-treatment-daughter.print',
 'https://www.foxnews.com/world/israel-strikes-hamas-gaza-surprise-attack-exchanges-fire-hezbollah',
 'https://www.foxnews.com/entertainment/taylor-swift-travis-kelce-get-support-from-family-after-surprise-eras-tour-stage-appearance',
 'https://www.foxnews.com/entertainment/jim-morrison-the-doors-memoir-robby-krieger',
 'https://www.foxnews.com/politics/walz-repeats-georgia-abortion-death-falsehood-decried-doctors-fearmongering',
 'https://www.foxnews.com/politics/harris-campaign-wont-give-details-type-gun-she-owns-last-time-she-went-range',
 'https://www.foxnews.com/us/utah-mom-kept-missing-daughter-hidden-cult-compound-months-help-from-adult-sons-prosecutors',
 'https://www.foxnews.com/media/kamala-harris-far-left-record-dismissed-accusations-attacks-from-trump-gop-shes-moderate',
 'https://www.foxnews.com/world/israel-defense-forces-confirm-targeted-strike-beirut',
 'https://www.foxnews.com/world/pope-emeritus-benedict-xvi-dead-95-vatican-says',
 'https://www.foxnews.com/politics/sheldon-whitehouse-doesnt-denounce-all-white-beach-club-his-family-belongs-to',
 'https://www.foxnews.com/sports/san-jose-state-womens-volleyballs-trans-player-raises-eyebrows-brutal-spike-vs-new-mexico.print',
 'https://www.foxnews.com/entertainment/star-wars-actress-carrie-fisher-honored-star-hollywood-walk-of-fame-amid-family-drama',
 'https://www.foxnews.com/politics/aoc-fires-back-fetterman-accuses-him-bleak-dunk-attempt',
 'https://www.foxnews.com/media/harris-calls-americans-move-past-failed-policies-november-draws-mockery.print',
 'https://www.foxnews.com/entertainment/jake-e-lee-guitarist-ozzy-osbourne-broke-rib-damaged-lung-shot-3-times.print',
 'https://www.foxnews.com/sports/nevada-womens-volleyball-captain-slams-trans-athletes-her-sport-team-decides-against-players-refusal.print',
 'https://www.foxnews.com/media/jd-vance-calls-out-deranged-mindset-we-need-illegal-immigrants-build-houses',
 'https://www.foxnews.com/lifestyle/meet-american-who-created-bubble-gum-walter-diemer-home-kitchen-chemist-outwitted-scientists',
 'https://www.foxnews.com/politics/biden-campaign-sends-all-staff-memo-hoping-calm-post-debate-concerns-report',
 'https://www.foxnews.com/politics/trump-harris-toss-up-races-key-swing-states-pennsylvania-georgia-nevada-poll.print',
 'https://www.foxnews.com/politics/harris-supporters-say-shell-fix-immigration-blame-trump-for-border-crisis-immigration-blame-trump-border-crisis',
 'https://www.foxnews.com/world/israel-says-conducted-retaliatory-strikes-against-hezbollah-lebanon-struck-hamas-gaza.print',
 'https://www.foxnews.com/entertainment/harrison-ford-mocks-conan-obrien-star-wars-dis-cant-f-ing-remember',
 'https://www.foxnews.com/lifestyle/franklin-grahams-samaritans-purse-sponsors-21-ambulances-israel-replace-destroyed-hamas',
 'https://www.foxnews.com/entertainment/bruce-willis-shares-sweet-embrace-daughter-tallulah-makes-funny-faces-playful-snaps.print',
 'https://www.foxnews.com/politics/secret-service-protocol-changed-amid-presidential-assassination-attempts-through-years',
 'https://www.foxnews.com/world/hezbollah-hits-israel-deadliest-attack-months-long-conflict-idf-says-raising-fears-escalation.print',
 'https://www.foxnews.com/media/fox-nation-debut-american-history-series-kelsey-grammer',
 'https://www.foxnews.com/politics/trump-calls-liz-cheney-low-iq-war-hawk-after-appearance-support-harris',
 'https://www.foxnews.com/media/trump-hints-he-appear-joe-rogan-podcast-i-think-im-doing-it.print',
 'https://www.foxnews.com/us/stairwell-b-story-14-survivors-north-tower-9-11',
 'https://www.foxnews.com/lifestyle/best-vegetables-for-health-nutritionists',
 'https://www.foxnews.com/sports/eagles-nick-sirianni-has-heated-spat-fans-after-close-win-vs-browns',
 'https://www.foxnews.com/lifestyle/americas-unique-thanksgiving-stuffing-preferences-state-by-state',
 'https://www.foxnews.com/politics/wisconsin-kicks-off-election-season-first-widely-available-absentee-ballots.print',
 'https://www.foxnews.com/media/kamala-harris-struggling-how-shes-different-biden-the-view-surprises-cnn-panel.print',
 'https://www.foxnews.com/sports/transgender-athlete-defeated-woman-competitor-major-uk-competition-championship-epic-comeback.print',
 'https://www.foxnews.com/politics/black-lives-matter-blames-us-praises-cuban-regime-social-media-erupts',
 'https://www.foxnews.com/politics/how-us-government-dole-out-aid-victims-hurricanes-milton-helene',
 'https://www.foxnews.com/politics/biden-admin-rushing-industrialize-us-oceans-stop-climate-change-environmental-wrecking-ball',
 'https://www.foxnews.com/us/honduran-illegal-immigrant-deported-twice-sentenced-texas-burglary-ring',
 'https://www.foxnews.com/us/colorado-mayor-speaks-out-after-video-armed-venezuelan-gang-apartment-goes-viral.print',
 'https://www.foxnews.com/us/remains-of-kansas-priest-who-died-in-korean-war-identified.print',
 'https://www.foxnews.com/us/anti-israel-yale-protesters-joining-columbia-students-in-tear-down-our-society-ivy-league-movement-law-prof',
 'https://www.foxnews.com/sports/idaho-gov-praises-boise-states-decision-forfeit-womens-volleyball-match-against-team-trans-player',
 'https://www.foxnews.com/entertainment/billy-joel-weight-loss-madison-square-garden',
 'https://www.foxnews.com/food-drink/tequila-more-than-shot-fun-facts-spirit',
 'https://www.foxnews.com/lifestyle/americans-need-face-face-civil-discussions-folks-outside-bubble.print',
 'https://www.foxnews.com/media/mom-dad-complain-11-year-old-daughter-forced-share-bed-biological-male-school-trip',
 'https://www.foxnews.com/media/slap-face-media-government-downplaying-venezuelan-gangs-says-woman-fled-colorado-apartment',
 'https://www.foxnews.com/us/seven-deadly-sins-biker-gang-founder-kills-7-people-dog.print',
 'https://www.foxnews.com/politics/trump-indicted-second-time-election-subversion-case-brought-special-counsel-jack-smith.print',
 'https://www.foxnews.com/sports/san-jose-state-police-battle-womens-volleyball-transgender-culture-war',
 'https://www.foxnews.com/politics/power-rankings-trump-maintains-lead-two-top-issues-ahead-vp-debate',
 'https://www.foxnews.com/entertainment/kate-moss-50-victorias-secret-fashion-show-surprise-appearance-daughter-lila-22',
 'https://www.foxnews.com/politics/5-more-house-democrats-call-biden-drop-out#&_intcmp=fnhpbt5',
 'https://www.foxnews.com/politics/riley-gaines-visits-rnc-message-new-york-ag-letitia-james-democrats-claiming-party-women.print',
 'https://www.foxnews.com/entertainment/hilary-duff-how-i-met-your-father-series-sequel-hulu',
 'https://www.foxnews.com/politics/flashback-harris-campaign-senior-adviser-several-insensitive-comments-women-gay-people',
 'https://www.foxnews.com/politics/michigan-becomes-top-gop-senate-target-mike-rogers-ties-dem-opponent-among-older-voters',
 'https://www.foxnews.com/sports/american-women-players-settle-suit-vs-us-soccer-for-24m',
 'https://www.foxnews.com/sports/herschel-walker-says-obama-forgot-our-fight-right-vote-after-scolding-black-voters-against-harris',
 'https://www.foxnews.com/us/would-be-trump-assassin-wants-judge-cannon-recuse-herself-dismissing-document-case.print',
 'https://www.foxnews.com/politics/nj-announces-emergency-dune-repairs-shore-town-penalized-doing-itself',
 'https://www.foxnews.com/media/cnn-political-director-warns-trouble-sign-harris-she-lags-white-male-voters-key-states',
 'https://www.foxnews.com/food-drink/japanese-souffle-pancake-gaining-popularity-us-origin-story-hawaii-15-years-ago',
 'https://www.foxnews.com/lifestyle/garlic-planting-roasting-cooking-health-benefits',
 'https://www.foxnews.com/sports/olympic-boxer-deemed-have-male-chromosomes-wins-fight-46-seconds-opponent-left-tears-after-hard-hits',
 'https://www.foxnews.com/sports/womens-volleyball-team-transgender-player-getting-police-security-amid-backlash-lawsuit',
 'https://www.foxnews.com/politics/oprah-winfrey-makes-surprise-dnc-appearance-rail-against-man-she-once-considered-running-office',
 'https://www.foxnews.com/media/cnn-brian-stelter-reliable-sources-2021.print',
 'https://www.foxnews.com/world/german-bureaucrat-under-fire-trashing-british-wwii-hero-inspired-israeli-army',
 'https://www.foxnews.com/us/sniper-killed-would-be-trump-assassin-one-million-shot-source',
 'https://www.foxnews.com/politics/rfk-jr-corporate-media-attacked-more-president-trump',
 'https://www.foxnews.com/politics/harris-trump-showdown-leading-law-enforcement-group-takes-sides-presidential-election',
 'https://www.foxnews.com/media/cnn-brian-stelter-hunter-biden-disinformation-conference',
 'https://www.foxnews.com/food-drink/tiktok-video-fast-food-restaurant-shows-how-speedy-machine-makes-salad-bowl-no-time',
 'https://www.foxnews.com/lifestyle/this-day-history-feb-17-1801-jefferson-elected-president-party-politics-nation',
 'https://www.foxnews.com/media/fox-news-channel-dominates-cnn-msnbc-during-historic-news-cycle-of-third-quarter.print',
 'https://www.foxnews.com/media/biden-called-out-border-crisis-texas-democrat-absolutely-president-should-be-here',
 'https://www.foxnews.com/politics/biden-admin-unveils-sweeping-new-actions-increasing-costs-oil-gas-leasing',
 'https://www.foxnews.com/media/cnn-brian-stelter-andrew-cuomo-leadership-hope-not-false-hope.print',
 'https://www.foxnews.com/lifestyle/texas-woman-accidentally-swallows-partial-dentures-how-medical-team-saved',
 'https://www.foxnews.com/entertainment/americas-got-talent-judge-heidi-klum-did-not-expect-9-year-olds-epic-tina-turner-performance',
 'https://www.foxnews.com/health/study-reveals-extreme-weathers-impact-seniors-attendance-doctor-appointments',
 'https://www.foxnews.com/lifestyle/this-day-history-feb-12-1809-abraham-lincoln-born-kentucky',
 'https://www.foxnews.com/lifestyle/national-pow-mia-recognition-day-reminds-americans-nobility-war-heroes-ongoing-need-do-better.print',
 'https://www.foxnews.com/food-drink/7-sneaky-calorie-culprits-healthy-green-salad',
 'https://www.foxnews.com/sports/national-womens-soccer-league-faces-lawsuit-former-employee-alleges-sexual-assault',
 'https://www.foxnews.com/lifestyle/tony-bennett-own-words-i-feel-i-have-been-truly-blessed',
 'https://www.foxnews.com/lifestyle/this-day-history-april-1-1945-us-forces-invade-okinawa-last-major-battle-wwii',
 'https://www.foxnews.com/politics/esper-replacement-chris-miller-tells-us-troops-its-time-to-come-home',
 'https://www.foxnews.com/lifestyle/armed-forces-day-honor-flight-mission-bbq',
 'https://www.foxnews.com/lifestyle/thanksgiving-casserole-preferences-state-google-trends',
 'https://www.foxnews.com/media/kamala-harris-tells-the-view-she-cant-think-anything-she-would-have-done-differently-from-biden.print',
 'https://www.foxnews.com/politics/balance-power-trump-campaign-slams-sen-tester-radically-out-touch-after-abortion-ad-rollout',
 'https://www.foxnews.com/politics/from-shark-tank-campaign-trail-mark-cuban-teams-up-kamala-harris.print',
 'https://www.foxnews.com/politics/supreme-court-rules-favor-colorado-graphic-designer-refused-create-same-sex-wedding-websites',
 'https://www.foxnews.com/food-drink/great-weeknight-dinner-classic-meatballs-garlic-bread-chef-favorite.print',
 'https://www.foxnews.com/us/virginia-teacher-shot-6-year-old-student-classroom-says-shell-never-forget-look-face',
 'https://www.foxnews.com/entertainment/shawn-mendes-camila-cabello-split-break-up-relationship',
 'https://www.foxnews.com/media/kamala-harris-dnc-undertaking-largest-gaslighting-operation-history-politics-says-house-speaker',
 'https://www.foxnews.com/us/illegal-immigrants-terrorism-ties-exploit-border-homeland-security-warns',
 'https://www.foxnews.com/health/mother-frantic-save-clinical-trial-could-cure-daughter-treatment-sitting-fridge.print',
 'https://www.foxnews.com/media/ted-nugent-tucker-carlson-fox-nation-constitution-bear-arms.print',
 'https://www.foxnews.com/media/analysis-finds-americans-need-extra-11400-afford-basics-gop-lawmakers-blame-bidenomics',
 'https://www.foxnews.com/entertainment/matt-damons-advice-josh-hartnett-while-filming-oppenheimer-so-unhelpful',
 'https://www.foxnews.com/us/former-secret-service-agent-warns-agency-stretched-thin-new-responsibilities-lack-manpower',
 'https://www.foxnews.com/media/new-book-shows-alleged-biden-harris-divide-surfaced-earlier-previous-president-vp-rifts-critics.print',
 'https://www.foxnews.com/us/venezuelan-tren-de-aragua-gang-recruiting-kids-out-texas-middle-schools.print',
 'https://www.foxnews.com/entertainment/jelly-roll-gives-powerful-testimony-congress-fentanyl-part-problem',
 'https://www.foxnews.com/politics/video-resurfaces-harris-chanting-down-deportation-2018-parade-disgraced-actor',
 'https://www.foxnews.com/media/thousands-anti-israel-protesters-descend-white-house-praising-hamas-slamming-genocide-joe',
 'https://www.foxnews.com/politics/haitian-migration-roils-town-battleground-state-signs-pro-trump-support-rise.print',
 'https://www.foxnews.com/lifestyle/105-year-old-woman-graduates-stanford-university-83-years-leaving-campus-amazing',
 'https://www.foxnews.com/official-polls/fox-news-poll-trump-hedge-biden-potential-2024-rematch',
 'https://www.foxnews.com/lifestyle/meet-the-american-who-first-recorded-blues-nations-original-pop-diva-mamie-smith',
 'https://www.foxnews.com/travel/replica-anne-frank-hidden-annex-unveiled-new-york-city',
 'https://www.foxnews.com/sports/who-imane-khelif-algerian-olympic-boxer-deemed-have-male-chromosomes.print',
 'https://www.foxnews.com/lifestyle/from-salmon-shark-best-worst-fish-health-according-experts',
 'https://www.foxnews.com/politics/white-house-communism-failed-ideology-historic-cuba-protests',
 'https://www.foxnews.com/lifestyle/arizona-grandma-man-she-mistakenly-texted-share-thanksgiving-7th-straight-year-since-2016',
 'https://www.foxnews.com/media/tim-walz-turns-down-ny-times-interview-requests-about-response-george-floyd-riots',
 'https://www.foxnews.com/us/new-york-anti-israel-rally-un-features-sign-supporting-terror-group-hezbollah',
 'https://www.foxnews.com/opinion/im-cake-artist-who-won-supreme-court-heres-why-im-still-court.print',
 'https://www.foxnews.com/media/black-farmers-sue-biden-administration-broken-debt-relief-promise-president-reneged-meeting',
 'https://www.foxnews.com/us/good-samaritan-helps-drag-wounded-houston-cop-out-highway-gunfight.print',
 'https://www.foxnews.com/world/israeli-military-says-regular-infantry-armored-units-joining-limited-ground-operation-southern-lebanon.print',
 'https://www.foxnews.com/media/rfk-jr-shrugs-off-biden-family-corruption-allegations-wont-spear-tip-campaign',
 'https://www.foxnews.com/politics/tens-thousands-illegal-immigrants-sexual-assault-homicide-convictions-roaming-us-streets.print',
 'https://www.foxnews.com/politics/biden-admin-issues-warning-netanyahu-israel-holds-emergency-meeting-gaza-aid.print',
 'https://www.foxnews.com/lifestyle/mothers-day-one-liners-life-advice-real-moms.print',
 'https://www.foxnews.com/lifestyle/mike-rowe-announces-something-stand-film-celebrating-america',
 'https://www.foxnews.com/tech/how-score-cheap-stuff-keep-resell',
 'https://www.foxnews.com/lifestyle/rural-travel-destinations-unplug-fun-summer',
 'https://www.foxnews.com/entertainment/charlie-sheen-denise-richards-support-sami-sheen-onlyfans',
 'https://www.foxnews.com/politics/pentagon-sending-few-thousand-us-troops-middle-east-one-day-after-biden-promised-he-wouldnt',
 'https://www.foxnews.com/us/trump-meets-rachel-morin-family-border-maryland-mom-5-murdered-illegal-immigrant-suspect.print',
 'https://www.foxnews.com/politics/top-adviser-left-wing-california-da-charged-nearly-dozen-felonies',
 'https://www.foxnews.com/media/cnn-jeff-zucker-david-chalian-hunter-biden-project-veritas',
 'https://www.foxnews.com/lifestyle/this-day-history-august-25-1980-broadway-musical-42nd-street-opens',
 'https://www.foxnews.com/politics/comedian-jim-gaffigan-takes-surprising-shot-harris-skipping-catholic-met-gala',
 'https://www.foxnews.com/politics/kamala-harris-finally-fields-questions-press-dodging-media-18-days-since-becoming-dem-nominee',
 'https://www.foxnews.com/politics/trump-harris-debate-sen-rick-scott-identifies-biggest-thing-can-help-former-president',
 'https://www.foxnews.com/politics/biden-approval-rating-plummets-15-year-low-poll-finds.print',
 'https://www.foxnews.com/politics/supreme-court-denies-biden-administration-appeal-over-federal-emergency-abortion-requirement-texas',
 'https://www.foxnews.com/lifestyle/devices-to-help-sleep-better',
 'https://www.foxnews.com/entertainment/pink-slammed-biden-harris-shirt-husband-carey-hart-defends',
 'https://www.foxnews.com/official-polls/fox-news-poll-harris-trump-dead-heat-pennsylvania',
 'https://www.foxnews.com/world/videos-hamas-brutality-toward-israelis-eerily-reminiscent-isis-tactics.print',
 'https://www.foxnews.com/politics/trump-keeps-massive-lead-haley-ties-desantis-second-new-2024-gop-presidential-primary-poll',
 'https://www.foxnews.com/politics/bernie-sanders-force-senate-vote-resolution-could-freeze-aid-israel',
 'https://www.foxnews.com/media/sage-steele-calls-out-obama-scolding-black-men-lack-enthusiasm-kamala-harris-back-off',
 'https://www.foxnews.com/health/new-drug-stiff-person-syndrome-granted-designation-speed-development-thrilled-community',
 'https://www.foxnews.com/entertainment/sydney-sweeney-glad-mother-stopped-getting-breast-reduction-teen',
 'https://www.foxnews.com/politics/longtime-pa-dem-silent-on-support-for-freshman-squad-member-after-his-name-is-quietly-removed-from-site',
 'https://www.foxnews.com/entertainment/bruce-willis-daughter-tallulah-gets-emotional-photos-dad-my-whole-damn-heart',
 'https://www.foxnews.com/politics/extreme-agenda-harris-past-record-illegal-immigration-resurfaces-after-biden-drops-out.print',
 'https://www.foxnews.com/science/discovery-civil-war-map-antietam',

## Description Example

Run example scraping code from project description document.

In [4]:
import requests
from bs4 import BeautifulSoup

url = "https://www.foxnews.com/sports/juan-soto-sends-yankees-world-series-first-time-15-years" # example website

response = requests.get(url)
if response.status_code != 200:
    raise Exception(f"Failed to load page: Status code {response.status_code}")

# Parse the HTML content with BeautifulSoup
soup = BeautifulSoup(response.text, "html.parser")

title = soup.find("h1", class_="headline speakable")

# title should be the following
# Juan Soto sends the Yankees to the World Series for the first time in years

In [5]:
title.get_text()

'Juan Soto sends the Yankees to the World Series for the first time in 15 years'

## Scraping first 50 urls

Write function to get first 50 headlines from list of urls.

In [ ]:
# Get first 50 titles and store in an array -> do we need to
# throttle requests? it's not hitting the same link right?
import time
from requests.exceptions import RequestException
from collections import defaultdict
import random

def get_headlines(urls: list[str], verbose = False) -> dict[str, list[str]]:
    headlines = defaultdict(list)
    for url in urls:
        time.sleep(random.randint(1,3))
        print(url) if verbose else ""
        source = "fox" if "fox" in url else "nbc"
        
        try: 
            response = requests.get(url)
            response.raise_for_status()
        except RequestException as e:
            print(f"Error {e}. Trying again.")
            
            try:
                time.sleep(5)
                response = requests.get(url)
                response.raise_for_status()
            except:
                print(f"Error again: {e}. Skipping {url}")
                continue
        
        else:
            soup = BeautifulSoup(response.text, "html.parser")
            title = soup.find("h1", class_ = "headline speakable")
            headlines[source].append(title.get_text() if title else None)
        
    return headlines

In [7]:
urls = list(links["url"])[0:50]
headlines = get_headlines(urls = urls)

### Results

Display results and make sure all pages were successfully scraped.

In [8]:
import pprint
pprint.pprint(headlines)

defaultdict(<class 'list'>,
            {'fox': ["Jack Carr recalls Gen. Eisenhower's D-Day memo about "
                     "'great and noble undertaking'",
                     'Bruce Willis, Demi Moore avoided doing one thing while '
                     'co-parenting, daughter says',
                     None,
                     'Emily Blunt says her ‘toes curl’ when people tell her '
                     "their kids want to act: 'I want to say, don’t do it!'",
                     "'The View' co-host, CNN commentator Ana Navarro to host "
                     'night 2 of Democratic National Convention',
                     None,
                     None,
                     "Tom Cotton turns tables on CNN's Dana Bash on guns, "
                     "brings up Harris' past remarks on school shootings",
                     'Kamala rides tsunami of positive press, but skeptics see '
                     'a risky choice',
                     "Harris' running mate faces renewed scrutiny after his "
                     "'weird' socialism comparison resurfaces",
                     'Israeli-American reservist killed by Hezbollah missile '
                     'in Israel, IDF says',
                     'David McCullough, American historian and Presidential '
                     'Medal of Freedom recipient, dies at 89',
                     'Web designer who refuses to create sites for same-sex '
                     'weddings says Colorado law violates free speech rights',
                     'Simon Cowell reveals how his son changed his judging '
                     'style: ‘I have much more empathy’',
                     'Rare Disease Day: Walking Dead Syndrome and other rare '
                     'conditions baffle doctors and researchers',
                     "CNN calls out Harris for using Trump's border wall in "
                     'campaign ad after condemning it for years',
                     'Taylor Swift steals NYC spotlight during dinner with '
                     'Blake Lively, Sophie Turner and Brittany Mahomes',
                     'Ozempic, the happy drug? Study suggests weight-loss '
                     'medications could reduce depression, anxiety',
                     None,
                     None,
                     'Israel declares war after Hamas surprise attack, '
                     'launches retaliatory airstrikes in Gaza',
                     'Taylor Swift, Travis Kelce get support from family after '
                     "surprise 'Eras Tour' stage appearance",
                     "The Doors' Jim Morrison had ‘a fascination with death’ "
                     'before passing away at 27, bandmate Robby Krieger says',
                     'Walz repeats Georgia abortion death falsehood decried by '
                     "doctors as 'fearmongering'",
                     "Harris campaign won't give details on type of gun she "
                     'owns, last time she went to range',
                     'Utah mom kept missing daughter, 5, hidden in cult '
                     "'compound' for months with help from adult sons: "
                     'prosecutors',
                     "Kamala Harris' far-left record dismissed as "
                     "'accusations,' attacks from Trump and GOP: 'She's "
                     "moderate'",
                     "Israel Defense Forces confirm 'targeted strike' on "
                     'Beirut',
                     'Pope Emeritus Benedict XVI dead at 95, Vatican says',
                     "Sheldon Whitehouse doesn't denounce super-exclusive "
                     'beach club his family belongs to',
                     None,
                     "'Star Wars' actress Carrie Fisher honored with star on "
                     'Hollywood Walk of Fame amid family drama',
                     "AOC fires back at Fetterman, accuses him of 'bleak dunk "
                     "attempt'",
                     None,
                     None,
                     None,
                     "JD Vance calls out 'deranged' mindset that we need "
                     'illegal immigrants to build houses',
                     'Meet the American who created bubble gum, Walter Diemer, '
                     'home-kitchen chemist outwitted scientists',
                     'Biden campaign sends all-staff memo hoping to calm '
                     'post-debate concerns',
                     None,
                     "Harris supporters say she'll fix immigration, blame "
                     'Trump for border crisis',
                     None,
                     "Harrison Ford mocks Conan O’Brien after 'Star Wars' dis: "
                     "‘You can't f---ing remember'",
                     "Franklin Graham's Samaritan's Purse sponsors 21 "
                     'ambulances in Israel to replace those destroyed by Hamas',
                     None,
                     'How Secret Service protocol has changed amid '
                     'presidential assassination attempts through the years',
                     None,
                     'Fox Nation to debut new American history series hosted '
                     'by Kelsey Grammer',
                     "Trump calls Liz Cheney a 'low IQ war hawk' after "
                     'appearance in support of Harris',
                     None]})

In [10]:
len(headlines["fox"])

50

## Testing scraping workflow

Run through a full scraping process on first link in DF to make sure all selectors work. Code below is basically copy and pasted into `scripts/scrape_fox.py`.

In [ ]:
import pandas as pd
from bs4 import BeautifulSoup
import requests

In [8]:
link = links["url"][0]
link

'https://www.foxnews.com/lifestyle/jack-carrs-eisenhower-d-days-memo-noble-undertaking'

In [9]:
# Fetch link content
response = requests.get(link)
# Check if request was successful
if response.status_code != 200:
    raise Exception(f"Failed to load page: Status code {response.status_code}")
# Parse the HTML content with BeautifulSoup
soup = BeautifulSoup(response.text, "html.parser")

In [11]:
# Show soup
print(soup.prettify())

<!DOCTYPE html>
<html data-n-head="%7B%22lang%22:%7B%22ssr%22:%22en%22%7D%7D" data-n-head-ssr="" lang="en">
 <head>
  <title>
   Jack Carr recalls Eisenhower's D-Day memo about 'great and noble undertaking' | Fox News
  </title>
  <meta content="IE=edge,chrome=1" data-n-head="ssr" http-equiv="X-UA-Compatible"/>
  <meta content="text/html; charset=utf-8" data-hid="content-type" data-n-head="ssr" http-equiv="content-type"/>
  <meta content="on" data-hid="x-dns-prefetch-control" data-n-head="ssr" http-equiv="x-dns-prefetch-control"/>
  <meta charset="utf-8" data-n-head="ssr"/>
  <meta content="width=device-width, minimum-scale=1.0, initial-scale=1.0" data-hid="viewport" data-n-head="ssr" name="viewport"/>
  <meta content="//static.foxnews.com/static/orion/styles/img/fox-news/favicons/mstile-70x70.png" data-n-head="ssr" name="msapplication-square70x70logo"/>
  <meta content="//static.foxnews.com/static/orion/styles/img/fox-news/favicons/mstile-150x150.png" data-n-head="ssr" name="msapplication-square150x150logo"/>
  <meta content="//static.foxnews.com/static/orion/styles/img/fox-news/favicons/mstile-310x310.png" data-n-head="ssr" name="msapplication-square310x310logo"/>
  <meta content="//static.foxnews.com/static/orion/styles/img/fox-news/favicons/mstile-310x150.png" data-n-head="ssr" name="msapplication-wide310x150logo"/>
  <meta content="en" data-hid="content-language" data-n-head="ssr" http-equiv="content-language"/>
  <meta content="Bestselling author Jack Carr, former Navy SEAL, recalls Gen. Dwight Eisenhower's words issued on June 5, 1944, just ahead of D-Day during World War II — 80 years ago this week." data-hid="description" data-n-head="ssr" name="description"/>
  <meta content="fnc" data-hid="prism.channel" data-n-head="ssr" name="prism.channel"/>
  <meta content="lifestyle" data-hid="prism.section" data-n-head="ssr" name="prism.section"/>
  <meta content="" data-hid="prism.subsection1" data-n-head="ssr" name="prism.subsection1"/>
  <meta content="" data-hid="prism.subsection2" data-n-head="ssr" name="prism.subsection2"/>
  <meta content="" data-hid="prism.subsection3" data-n-head="ssr" name="prism.subsection3"/>
  <meta content="" data-hid="prism.subsection4" data-n-head="ssr" name="prism.subsection4"/>
  <meta content="subsection" data-hid="prism.aggregationType" data-n-head="ssr" name="prism.aggregationType"/>
  <meta content="" data-hid="prism.genre" data-n-head="ssr" name="prism.genre"/>
  <meta content="article" data-hid="pagetype" data-n-head="ssr" name="pagetype"/>
  <meta content="tiger" data-hid="content-creator" data-n-head="ssr" name="content-creator"/>
  <meta content="Jack Carr" data-hid="dc.creator" data-n-head="ssr" name="dc.creator" scheme="dcterms.creator"/>
  <meta content="Jack Carr recalls Gen. Eisenhower's D-Day memo about 'great and noble undertaking'" data-hid="dc.title" data-n-head="ssr" name="dc.title"/>
  <meta content="" data-hid="dc.subject" data-n-head="ssr" name="dc.subject"/>
  <meta content="" data-hid="dcterms.abstract" data-n-head="ssr" name="dcterms.abstract"/>
  <meta content="Text.Article" data-hid="dc.type" data-n-head="ssr" name="dc.type" scheme="dcterms.DCMIType"/>
  <meta content="" data-hid="dc.description" data-n-head="ssr" name="dc.description"/>
  <meta content="en-US" data-hid="dc.language" data-n-head="ssr" name="dc.language" scheme="dcterms.RFC4646"/>
  <meta content="Fox News" data-hid="dc.publisher" data-n-head="ssr" name="dc.publisher"/>
  <meta content="text/html" data-hid="dc.format" data-n-head="ssr" name="dc.format" scheme="dcterms.IMT"/>
  <meta content="urn:uri:base64:122258d4-0fb5-548d-8ff0-6c2d9397eccd" data-hid="dc.identifier" data-n-head="ssr" name="dc.identifier" scheme="dcterms.URI"/>
  <meta content="Fox News" data-hid="dc.source" data-n-head="ssr" name="dc.source"/>
  <meta content="2024-06-04" data-hid="dc.date" data-n-head="ssr" name="dc.date"/>
  <meta content="2024-06-04T20:44:40-04:00" data-hid="dcterms.created" data-n-head="ssr" name="dcterms.created" scheme="dcterms.ISO8601"/>
  <meta content="2024-06-05T21:55:14-04:00" data-hid="dcterms.modified" data-n-head="ssr" name="dcterms.modified" scheme="dcterms.ISO8601"/>
  <meta content="Jack Carr recalls Gen. Eisenhower's D-Day memo about 'great and noble undertaking'" data-hid="og:title" data-n-head="ssr" property="og:title"/>
  <meta content="Bestselling author Jack Carr, former Navy SEAL, recalls Gen. Dwight Eisenhower's words issued on June 5, 1944, just ahead of D-Day during World War II — 80 years ago this week." data-hid="og:description" data-n-head="ssr" property="og:description"/>
  <meta content="article" data-hid="og:type" data-n-head="ssr" property="og:type"/>
  <meta content="https://static.foxnews.com/foxnews.com/content/uploads/2024/05/carr-split2.png" data-hid="og:image" data-n-head="ssr" property="og:image"/>
  <meta content="https://www.foxnews.com/lifestyle/jack-carrs-eisenhower-d-days-memo-noble-undertaking" data-hid="og:url" data-n-head="ssr" property="og:url"/>
  <meta content="Fox News" data-hid="og:site_name" data-n-head="ssr" property="og:site_name"/>
  <meta content="index, follow, max-image-preview:large, max-video-preview:-1" data-hid="robots" data-n-head="ssr" name="robots"/>
  <meta content="summary_large_image" data-n-head="ssr" name="twitter:card"/>
  <meta content="@foxnews" data-n-head="ssr" name="twitter:site"/>
  <meta content="Jack Carr recalls Gen. Eisenhower's D-Day memo about 'great and noble undertaking'" data-n-head="ssr" name="twitter:title"/>
  <meta content="Bestselling author Jack Carr, former Navy SEAL, recalls Gen. Dwight Eisenhower's words issued on June 5, 1944, just ahead of D-Day during World War II — 80 years ago this week." data-n-head="ssr" name="twitter:description"/>
  <meta content="https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2024/05/1024/512/carr-split2.png?ve=1&amp;tl=1" data-n-head="ssr" name="twitter:image"/>
  <meta content="https://www.foxnews.com/lifestyle/jack-carrs-eisenhower-d-days-memo-noble-undertaking" data-n-head="ssr" name="twitter:url"/>
  <meta content="113186182048399" data-n-head="ssr" property="fb:app_id"/>
  <meta content="false" data-n-head="ssr" property="article:opinion"/>
  <meta content="null" data-n-head="ssr" property="opt-active-exp"/>
  <meta content="true" data-n-head="ssr" property="foxid.gated"/>
  <meta content="/FOX NEWS/US/Military,/FOX NEWS/LIFESTYLE,/FOX NEWS/US/MILITARY/Veterans,/FOX NEWS/POLITICS/DEFENSE/Wars,/FOX NEWS/WORLD/WORLD REGIONS/Europe,/FOX NEWS/TOPIC/World War Two,/FOX NEWS/WORLD/WORLD REGIONS/France,/FOX NEWS/World" data-n-head="ssr" name="classification"/>
  <meta content="military,lifestyle,veterans,wars,europe,world-war-two,france,world" data-n-head="ssr" name="classification-isa"/>
  <meta content="lifestyle,military,veterans,wars,europe,world-war-two,france,world" data-n-head="ssr" name="classification-tags"/>
  <meta content="lifestyle, military, veterans, wars, europe, world war two, france, world" data-n-head="ssr" name="keywords"/>
  <meta content="false" data-n-head="ssr" name="tmp-pass-supported"/>
  <link crossorigin="true" data-n-head="ssr" href="https://fonts.gstatic.com" rel="preconnect"/>
  <link crossorigin="true" data-n-head="ssr" href="https://fonts.googleapis.com" rel="preconnect"/>
  <link crossorigin="true" data-n-head="ssr" href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,500;0,700;0,900;1,300;1,400&amp;display=swap" rel="stylesheet"/>
  <link data-n-head="ssr" href="//static.foxnews.com/static/orion/styles/img/fox-news/favicons/favicon.ico" rel="icon" type="image/x-icon"/>
  <link data-n-head="ssr" href="//static.foxnews.com/static/orion/styles/img/fox-news/favicons/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
  <link data-n-head="ssr" href="//static.foxnews.com/static/orion/styles/img/fox-news/favicons/apple-touch-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"/>
  <link data-n-head="ssr" href="//static.foxnews.com/static/orion/styles/img/fox-news/favicons/apple-touch-icon-60x60.png" rel="apple-touch-icon" sizes="60x60"/>
  <link data-n-head="ssr" href="//static.foxnews.com/static/orion/styles/img/fox-news/favicons/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"/>
  <link data-n-head="ssr" href="//static.foxnews.com/static/orion/styles/img/fox-news/favicons/apple-touch-icon-76x76.png" rel="apple-touch-icon" sizes="76x76"/>
  <link data-n-head="ssr" href="//static.foxnews.com/static/orion/styles/img/fox-news/favicons/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"/>
  <link data-n-head="ssr" href="//static.foxnews.com/static/orion/styles/img/fox-news/favicons/apple-touch-icon-120x120.png" rel="apple-touch-icon" sizes="120x120"/>
  <link data-n-head="ssr" href="//static.foxnews.com/static/orion/styles/img/fox-news/favicons/apple-touch-icon-144x144.png" rel="apple-touch-icon" sizes="144x144"/>
  <link data-n-head="ssr" href="//static.foxnews.com/static/orion/styles/img/fox-news/favicons/apple-touch-icon-152x152.png" rel="apple-touch-icon" sizes="152x152"/>
  <link data-n-head="ssr" href="//static.foxnews.com/static/orion/styles/img/fox-news/favicons/apple-touch-icon-180x180.png" rel="apple-touch-icon" sizes="180x180"/>
  <link data-n-head="ssr" href="//static.foxnews.com/static/orion/styles/img/fox-news/favicons/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>
  <link data-n-head="ssr" href="//static.foxnews.com/static/orion/styles/img/fox-news/favicons/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>
  <link data-n-head="ssr" href="//static.foxnews.com/static/orion/styles/img/fox-news/favicons/favicon-96x96.png" rel="icon" sizes="96x96" type="image/png"/>
  <link data-n-head="ssr" href="//static.foxnews.com/static/orion/styles/img/fox-news/favicons/android-chrome-192x192.png" rel="icon" sizes="192x192" type="image/png"/>
  <link as="script" data-n-head="ssr" href="https://c.amazon-adsystem.com/aax2/apstag.js" rel="preload"/>
  <link as="script" data-n-head="ssr" href="https://static.foxnews.com/static/strike/scripts/libs/prebid.js" rel="preload"/>
  <link as="script" data-n-head="ssr" fetchpriority="high" href="https://config.aps.amazon-adsystem.com/configs/3023" rel="preload"/>
  <link as="script" data-n-head="ssr" fetchpriority="high" href="https://client.aps.amazon-adsystem.com/publisher.js" rel="preload"/>
  <link crossorigin="true" data-n-head="ssr" href="//s.yimg.com" rel="preconnect"/>
  <link crossorigin="true" data-n-head="ssr" href="//securepubads.g.doubleclick.net" rel="preconnect"/>
  <link crossorigin="true" data-n-head="ssr" href="//c.amazon-adsystem.com" rel="preconnect"/>
  <link crossorigin="true" data-n-head="ssr" href="//ib.adnxs.com" rel="preconnect"/>
  <link crossorigin="true" data-n-head="ssr" href="//bidder.criteo.com" rel="preconnect"/>
  <link crossorigin="true" data-n-head="ssr" href="//as-sec.casalemedia.com" rel="preconnect"/>
  <link crossorigin="true" data-n-head="ssr" href="//foxnews-d.openx.net" rel="preconnect"/>
  <link crossorigin="true" data-n-head="ssr" href="//hbopenbid.pubmatic.com" rel="preconnect"/>
  <link crossorigin="true" data-n-head="ssr" href="//fastlane.rubiconproject.com" rel="preconnect"/>
  <link crossorigin="true" data-n-head="ssr" href="//sofia.trustx.org" rel="preconnect"/>
  <link crossorigin="true" data-n-head="ssr" href="//amprtc.media.net" rel="preconnect"/>
  <link data-n-head="ssr" href="https://aax.amazon-adsystem.com" rel="preconnect"/>
  <link data-n-head="ssr" href="https://www.foxnews.com/lifestyle/jack-carrs-eisenhower-d-days-memo-noble-undertaking" hreflang="x-default" rel="alternate"/>
  <link data-n-head="ssr" href="https://www.foxnews.com/lifestyle/jack-carrs-eisenhower-d-days-memo-noble-undertaking" rel="canonical"/>
  <link data-n-head="ssr" href="https://www.foxnews.com/rss.xml?category=lifestyle" rel="alternate" title="Latest Breaking News, News, Rumors" type="application/rss+xml"/>
  <link data-n-head="ssr" href="https://www.foxnews.com/lifestyle/jack-carrs-eisenhower-d-days-memo-noble-undertaking.amp" rel="amphtml"/>
  <link as="image" data-n-head="ssr" href="https://a57.foxnews.com/cf-images.us-east-1.prod.boltdns.net/v1/static/694940094001/549a40ae-f29d-4523-962b-729db963cd6d/6b3e843d-1ccd-494b-9411-113a8492b3cb/877x493/match/1280/720/image.jpg?ve=1&amp;tl=1" rel="preload"/>
  <link data-n-head="ssr" href="//static.foxnews.com/static/orion/styles/css/fox-news/article.rs.css" rel="stylesheet"/>
  <script data-n-head="ssr" src="//static.foxnews.com/static/orion/scripts/core/ag.core.js">
  </script>
  <script data-n-head="ssr" src="//global.fncstatic.com/static/isa/core.js">
  </script>
  <script data-n-head="ssr" src="//static.foxnews.com/static/strike/ver/foxnews/loader.global.js">
  </script>
  <script data-n-head="ssr" type="text/javascript">
   window.foxstrike.cmd.push(function(Strike) {
      Strike.setPageMetadata({"isGated":true,"channel":"fnc","pageType":"article","section":"lifestyle","sectionAcronym":"life"});
    });
  </script>
  <script data-n-head="ssr" type="application/ld+json">

In [39]:
# Extract article topic, headline, subtitle, author, date posted
topic_span = soup.find("span", class_ = "eyebrow")
topic = topic_span.get_text() if topic_span else None

title_h1 = soup.find("h1", class_ = "headline speakable")
title = title_h1.get_text() if title_h1 else None

subtitle_h2 = soup.find("h2", class_ = "sub-headline speakable")
subtitle = subtitle_h2.get_text() if subtitle_h2 else None

# Author
author_div = soup.find("div", class_ = "author-byline")
author = author_div.find_all("a")[0].get_text() if author_div else None

# Date posted
date_posted_time= soup.find("time")
datetime_posted = date_posted_time.get("datetime") if date_posted_time else None

In [42]:
# create dict
article_info = {
    "url": link,
    "topic": topic,
    "title": title,
    "subtitle": subtitle,
    "author": author,
    "datetime_posted": datetime_posted,
    "label": "Fox News"
}

## Splitting links into Fox News and NBC News dfs

Since we split up scraping responsibilities by news outlet, this section just splits the links df by it's news outlet url. There are also some cells confirming that we properly split the data between NBC and Fox.

In [4]:
links

                                                    url
0     https://www.foxnews.com/lifestyle/jack-carrs-e...
1     https://www.foxnews.com/entertainment/bruce-wi...
2     https://www.foxnews.com/politics/blinken-meets...
3     https://www.foxnews.com/entertainment/emily-bl...
4     https://www.foxnews.com/media/the-view-co-host...
...                                                 ...
3800  https://www.nbcnews.com/politics/2024-election...
3801  https://www.nbcnews.com/select/shopping/best-a...
3802  https://www.nbcnews.com/select/shopping/best-v...
3803  https://www.nbcnews.com/politics/2024-election...
3804  https://www.nbcnews.com/select/shopping/white-...

[3805 rows x 1 columns]

In [21]:
fox_links = links[links["url"].str.contains("foxnews.com")]

In [22]:
fox_links[fox_links["url"].str.contains("nbcnews")]

Empty DataFrame
Columns: [url]
Index: []

In [23]:
fox_links

                                                    url
0     https://www.foxnews.com/lifestyle/jack-carrs-e...
1     https://www.foxnews.com/entertainment/bruce-wi...
2     https://www.foxnews.com/politics/blinken-meets...
3     https://www.foxnews.com/entertainment/emily-bl...
4     https://www.foxnews.com/media/the-view-co-host...
...                                                 ...
1995  https://www.foxnews.com/official-polls/fox-new...
1996  https://www.foxnews.com/politics/trump-harris-...
1997  https://www.foxnews.com/world/biden-admin-outl...
1998  https://www.foxnews.com/politics/kamala-harris...
1999  https://www.foxnews.com/politics/pennsylvanian...

[2000 rows x 1 columns]

In [ ]:
fox_links.to_csv("../data/external/fox_news_urls.csv", index = False) # Writing just Fox to CSV bc idk how Joe did his part yet.

In [24]:
nbc_news = links[~links["url"].str.contains("foxnews.com")]